### ISSUE TITLE
Pod fails validation with Xcode 12 toolchain

### ISSUE THREAD

**Issue by mokagio** [jedisct1/swift-sodium#213]
Hi all 👋 Thank you for the great work building and maintaining this library. We use it in [one of our libraries at Automattic](https://github.com/Automattic/Automattic-Tracks-iOS/blob/5f96537a62a8b7d3eb6635cb4dd8489dd39fc62a/Automattic-Tracks-iOS.podspec#L35).

I'm experiencing an issue with the Xcode 12 toolchain and CocoaPods: the `.podspec` validation fails with this error:

```
❌ ld: in /path/to/CocoaPods-Lint/workspace/Pods/Sodium/Sodium/libsodium/libsodium-ios.a(libsodium_la-aead_xchacha20poly1305.o), 
building for iOS Simulator, 
but linking in object file built for iOS,
for architecture arm64

❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

You can reproduce this on `0.8.0` by running:

```
pod spec lint ./Sodium.podspec
```

I been able to get the validation to pass for version `0.8.0` for iOS and macOS, but not for watchOS. [Here's the branch on my fork](https://github.com/mokagio/swift-sodium/tree/exclude-arm64-architecture) if you want to check it out.

But, `master` has changed the way `libsodium` is imported with the `.xcframework` (which is pretty neat) and unfortunately the pod validation fails there, too 😞 .

I tried with CocoaPods 1.9.3 and also 1.10.0.rc.1. Here's the validation output from the latter:

```
- NOTE  | [iOS] xcodebuild:  warning:
  [CP] Unable to find matching .xcframework slice in 
  'Sodium/Clibsodium.xcframework Clibsodium library
  ios-arm64_x86_64-maccatalyst ios-i386_x86_64-simulator
  ios-arm64_armv7_armv7s' for the current build architectures
  (arm64 i386 x86_64).
- ERROR | xcodebuild:  Sodium/Sodium/Aead.swift:2:8: error: 
  no such module 'Clibsodium'
- NOTE  | [OSX] xcodebuild:  clang: error:
  linker command failed with exit code 1 (use -v to see invocation)
- NOTE  | [watchOS] xcodebuild:  warning:
 [CP] Unable to find matching .xcframework slice in 
 'Sodium/Clibsodium.xcframework Clibsodium library 
 watchos-i386_x86_64-simulator watchos-arm64_32_armv7k'
 for the current build architectures (arm64 i386 x86_64).
```

<details>
<summary>Click here for the full output</summary>

```
 -> Sodium (0.9.0)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'Sodium/Clibsodium.xcframework Clibsodium library ios-arm64_x86_64-maccatalyst ios-i386_x86_64-simulator ios-arm64_armv7_armv7s' for the current build architectures (arm64 i386 x86_64).
    - ERROR | xcodebuild:  Sodium/Sodium/Aead.swift:2:8: error: no such module 'Clibsodium'
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | [OSX] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [watchOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'Sodium/Clibsodium.xcframework Clibsodium library watchos-i386_x86_64-simulator watchos-arm64_32_armv7k' for the current build architectures (arm64 i386 x86_64).
```

</details>

This looks similar to #212, too.

Something that might be useful for debugging is running `pod spec lint --no-clean` to get access to the workspace that CocoaPods generates to do the linting. Something else is to use `--platforms=ios` (or `macos`, or `watchos`) to run the linting only on one platform.

Let me know what I can do to help solving this. I'll be poking around this more tomorrow.

**Comment by mokagio** [comment]
Update. I was able to get the Pod build and validation to work on watchOS against `0.8.0`.

I can't open a PR for it though, because you can only open PRs against branches and `0.8.0` is just a tag at this point.

I'll be looking at the `.xcframework` setup next.

@jedisct1, if I don't get anywhere with it or if you don't think the changes currently in `master` are ready to be shipped as part of a new version (I can see `0.9.0` has already been tagged, but hasn't been pushed to CocoaPods yet?) would you consider cutting out a patch version, `0.8.1`, to incorporate those CocoaPods fixes?

**Comment by mokagio** [comment]
While waiting for feedback from the maintainers on this issue, I published [a fork of this repo](https://cocoapods.org/pods/Sodium-Fork) with the fix to make it work with CocoaPods 1.9.3 and the Xcode 12.0 toolchain, on top of the 0.8.0 tag.

```ruby
# Podfile
pod 'Sodium-Fork'
```

```ruby
# YourPod.podspec
spec.dependency 'Sodium-Fork'
```

You might need to run `pod install --repo-update` or `pod repo update` to find it.

I also opened #214 against the main branch of the repo. Unfortunately, it doesn't get to the bottom of the issue –the validation still fails– but I think it's a step in the right direction so I thought I'd put it out there.

**Comment by mokagio** [comment]
After chatting with @jedisct1, we established that #214 will fix this issue on the main branch _once CocoaPods 1.10.0 is released_.

**Comment by fishercraigj** [comment]
Bumping to follow.  Same issue.  Kind of in a hole waiting for cocoapods to release v1.10.0 if that's the solution.

**Comment by FabioTacke** [comment]
Same here. ☝️
We've been waiting for the 1.10.0 release for a couple of weeks now. But at the moment there doesn't seem to be much movement around the issues being part of the 1.10.0 milestone.

**Comment by mokagio** [comment]
[CocoaPods 1.10.0 is out](https://rubygems.org/gems/cocoapods/versions/1.10.0) 🎉
